-- SQL script to create tables for airport and airline management system

-- AIRPORTS Table
CREATE TABLE airports (
    airport_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    location VARCHAR2(100) NOT NULL,
    country VARCHAR2(50) NOT NULL,
    CONSTRAINT uk_airport_name UNIQUE(name)
);

-- AIRLINES Table
CREATE TABLE airlines (
    airline_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    headquarters VARCHAR2(100) NOT NULL,
    CONSTRAINT uk_airline_name UNIQUE(name)
);

-- AIRCRAFTS Table
CREATE TABLE aircrafts (
    aircraft_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    model VARCHAR2(50) NOT NULL,
    capacity NUMBER NOT NULL,
    airline_id NUMBER NOT NULL,
    CONSTRAINT fk_aircraft_airline FOREIGN KEY (airline_id) REFERENCES airlines(airline_id),
    CONSTRAINT chk_capacity CHECK (capacity > 0)
);

-- FLIGHTS Table
CREATE TABLE flights (
    flight_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    airline_id NUMBER NOT NULL,
    aircraft_id NUMBER NOT NULL,
    departure_airport NUMBER NOT NULL,
    arrival_airport NUMBER NOT NULL,
    departure_time TIMESTAMP NOT NULL,
    arrival_time TIMESTAMP NOT NULL,
    fare NUMBER(10,2) NOT NULL,
    available_seats NUMBER NOT NULL,
    CONSTRAINT fk_flight_airline FOREIGN KEY (airline_id) REFERENCES airlines(airline_id),
    CONSTRAINT fk_flight_aircraft FOREIGN KEY (aircraft_id) REFERENCES aircrafts(aircraft_id),
    CONSTRAINT fk_flight_departure FOREIGN KEY (departure_airport) REFERENCES airports(airport_id),
    CONSTRAINT fk_flight_arrival FOREIGN KEY (arrival_airport) REFERENCES airports(airport_id),
    CONSTRAINT chk_fare CHECK (fare > 0),
    CONSTRAINT chk_available_seats CHECK (available_seats >= 0),
    CONSTRAINT chk_different_airports CHECK (departure_airport != arrival_airport),
    CONSTRAINT chk_arrival_after_departure CHECK (arrival_time > departure_time)
);

-- PASSENGERS Table
CREATE TABLE passengers (
    passenger_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    full_name VARCHAR2(100) NOT NULL,
    gender VARCHAR2(10) CHECK (gender IN ('Male', 'Female')),
    passport_number VARCHAR2(20) UNIQUE NOT NULL,
    nationality VARCHAR2(50) NOT NULL,
    contact_no VARCHAR2(20) NOT NULL
);

-- BOOKINGS Table
CREATE TABLE bookings (
    booking_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    passenger_id NUMBER NOT NULL,
    flight_id NUMBER NOT NULL,
    seat_no VARCHAR2(10) NOT NULL,
    booking_date DATE DEFAULT SYSDATE,
    status VARCHAR2(20) DEFAULT 'CONFIRMED' CHECK (status IN ('CONFIRMED', 'CANCELLED', 'PENDING')),
    CONSTRAINT fk_booking_passenger FOREIGN KEY (passenger_id) REFERENCES passengers(passenger_id),
    CONSTRAINT fk_booking_flight FOREIGN KEY (flight_id) REFERENCES flights(flight_id),
    CONSTRAINT uk_seat_per_flight UNIQUE(flight_id, seat_no)
);

-- TICKETS Table
CREATE TABLE tickets (
    ticket_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    booking_id NUMBER NOT NULL,
    issue_date DATE DEFAULT SYSDATE,
    payment_mode VARCHAR2(20) NOT NULL,
    total_amount NUMBER(10,2) NOT NULL,
    CONSTRAINT fk_ticket_booking FOREIGN KEY (booking_id) REFERENCES bookings(booking_id),
    CONSTRAINT chk_payment_mode CHECK (payment_mode IN ('Cash', 'Credit Card', 'Debit Card', 'Online')),
    CONSTRAINT chk_total_amount CHECK (total_amount > 0)
);

-- FLIGHT_AUDIT_LOG Table 
CREATE TABLE flight_audit_log (
    log_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    flight_id NUMBER NOT NULL,
    old_departure_time TIMESTAMP,
    new_departure_time TIMESTAMP,
    old_arrival_time TIMESTAMP,
    new_arrival_time TIMESTAMP,
    modified_date TIMESTAMP DEFAULT SYSTIMESTAMP,
    modified_by VARCHAR2(50) DEFAULT USER
);

--EMPLOYEES TABLE
CREATE TABLE employees (
  emp_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  username VARCHAR2(50) UNIQUE,
  full_name VARCHAR2(100),
  role VARCHAR2(50) NOT NULL CHECK (role IN ('ADMIN', 'MANAGER', 'AGENT'))
);

--HOLIDAYS TABLE
CREATE TABLE holidays (
    holiday_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    holiday_name VARCHAR2(100) NOT NULL,
    holiday_date DATE NOT NULL UNIQUE,
    description VARCHAR2(200),
    is_active CHAR(1) DEFAULT 'Y' CHECK (is_active IN ('Y', 'N'))
);


--AUDIT LOG TABLE
CREATE TABLE audit_log (
  audit_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  audit_user VARCHAR2(100),
  audit_action VARCHAR2(20), 
  audit_table VARCHAR2(50),
  audit_row_id VARCHAR2(100),
  audit_time TIMESTAMP DEFAULT SYSTIMESTAMP,
  details VARCHAR2(4000)
);

